src/main/java/kg/dutyfree/adminsystem/entity/Orders.java
package kg.dutyfree.adminsystem.entity;

import kg.dutyfree.adminsystem.entity.basic.AbstractEntity;
import kg.dutyfree.adminsystem.enums.OrdersEnum;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Objects;

@Entity
@Table(name = "orders")
@Access(AccessType.PROPERTY)
@ToString
public class Orders extends AbstractEntity<Long> {
    @Setter
    private Integer quantity;
    @Setter
    private Integer orderId;
    @Setter
    private Date createdAt;
    @Setter
    private Date updatedAt;
    @Setter
    private Date deletedAt;
    @Setter
    private SalespointWarehouse warehouse;
    @Setter
    private OrdersEnum status;

    @Column(name = "quantity", nullable = true)
    public Integer getQuantity() {
        return quantity;
    }

    @Column(name = "order_id", nullable = true)
    public Integer getOrderId() {
        return orderId;
    }

    @Column(name = "created_at", nullable = true)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getCreatedAt() {
        return createdAt;
    }

    @Column(name = "updated_at", nullable = true)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getUpdatedAt() {
        return updatedAt;
    }

    @Column(name = "deleted_at", nullable = true)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getDeletedAt() {
        return deletedAt;
    }

    @ManyToOne
    @JoinColumn(name = "sales_wh_id", referencedColumnName = "id")
    public SalespointWarehouse getWarehouse() {
        return warehouse;
    }


}

src/main/java/kg/dutyfree/adminsystem/controller/admin/OrdersBean.java
package kg.dutyfree.adminsystem.controller.admin;


import kg.dutyfree.adminsystem.beans.FilterExample;
import kg.dutyfree.adminsystem.controller.BaseBean;
import kg.dutyfree.adminsystem.entity.OrderDetails;
import kg.dutyfree.adminsystem.entity.Orders;
import kg.dutyfree.adminsystem.entity.Products;
import kg.dutyfree.adminsystem.entity.Salespoints;
import kg.dutyfree.adminsystem.enums.OrdersEnum;
import kg.dutyfree.adminsystem.enums.SortEnum;
import kg.dutyfree.adminsystem.model.OrderModel;
import kg.dutyfree.adminsystem.service.OrderDetailsService;
import kg.dutyfree.adminsystem.service.OrdersService;
import kg.dutyfree.adminsystem.service.ProductsService;
import kg.dutyfree.adminsystem.service.SalespointsService;
import lombok.Getter;
import lombok.Setter;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

/**
 * @author aziko
 */

@Named
@SessionScoped
public class OrdersBean extends BaseBean<Orders> {
    @EJB
    private OrdersService service;
    @EJB
    private SalespointsService salespointsService;
    @EJB
    private ProductsService productsService;
    @Getter
    @Setter
    private Products product;
    @Getter
    @Setter
    private Salespoints salespoint;
    @Getter
    @Setter
    private OrderDetails details;



    public void search() {

    }

    public void reset() {
        salespoint = null;
        product = null;
    }

    @Override
    protected List<FilterExample> getFilters() {
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        List<FilterExample> filters = super.getFilters();
//        filters.add(new FilterExample("createdAt",cal.getTime(), InequalityConstants.GREATER_EQUAL));
        return filters;
    }

    public void init(){
        list=service.findByExample(0,0, SortEnum.DESCENDING,getFilters(),"orderId");
//        orders=new OrderModel(service);
//        orders.setFilters(getFilters());
//        orders.setProperty("createdAt");
//        orders.setSortEnum(SortEnum.DESCENDING);
    }

    public void delete(Orders delete) {
        service.remove(delete);
    }

    @Override
    public String edit(Orders edit) {
        setEntity(edit);
        return super.edit(edit);
    }

    public String edit(Integer orderId,OrderDetails details) {
        list=service.findByProperty("orderId",orderId);
        this.details=details;
        return navigate("form.xhtml");
    }


    @Override
    public String add(){
        setEntity(new Orders());
        return super.add();
    }

    public String save(){
        return navigate("list.xhtml");
    }

    public List<Salespoints> getSalespoints(){
        return salespointsService.findAll();
    }
    public List<Products> getProducts(){
        return productsService.findAll();
    }
}

src/main/webapp/moderator/orders/form.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/layouts/private.xhtml">

    <ui:define name="top-content">

    </ui:define>

    <ui:define name="content">


        <h:form id="form" prependId="false">
            <p:growl sticky="true"/>

            <p:tabView>

                <p:tab title="#{msgs.order}">
                    <h:panelGrid columns="2" styleClass="form-table" columnClasses="form-table-odd-col"
                                 style="width: 440px;">

                        <h:outputLabel for="flightdate" value="#{msgs.flightdate}"/>
                        <p:inputText value="#{orderDetailsBean.entity.flightDate}" id="flightdate" styleClass="w-1-1" disabled="true"
                                     required="true" requiredMessage="#{msgs.flightdate} - #{errs.requiredField}"/>

                        <h:outputLabel for="fio" value="#{msgs.fio}"/>
                        <p:inputText value="#{orderDetailsBean.entity.fio}" id="fio" styleClass="w-1-1" disabled="true"
                                     required="true" requiredMessage="#{msgs.fio} - #{errs.requiredField}"/>

                        <h:outputLabel for="phone" value="#{msgs.phone}"/>
                        <p:inputText value="#{orderDetailsBean.entity.phone}" id="phone" styleClass="w-1-1" disabled="true"
                                     required="true" requiredMessage="#{msgs.phone} - #{errs.requiredField}"/>

                        <h:outputLabel for="orderid" value="#{msgs.orderid}"/>
                        <p:inputText value="#{orderDetailsBean.entity.orderId}" id="orderid" styleClass="w-1-1" disabled="true"
                                     required="true" requiredMessage="#{msgs.orderid} - #{errs.requiredField}"/>

                    </h:panelGrid>
                    <p:dataTable id="table" value="#{orderDetailsBean.ordersList}" var="orderDetails" paginator="false"
                                 tableStyleClass="display-table no-border no-bg text-left">
                        <p:column headerText="#{msgs.orderid}">
                            #{orderDetails.orderId}
                        </p:column>
                        <p:column headerText="#{msgs.product}">
                            #{orderDetails.warehouse.products.name}
                        </p:column>
                        <p:column headerText="#{msgs.salespoint}">
                            #{orderDetails.warehouse.salespoint.name}
                        </p:column>
                        <p:column headerText="#{msgs.price}">
                            #{orderDetails.warehouse.price}
                        </p:column>
                        <p:column headerText="#{msgs.quantity}">
                            #{orderDetails.quantity}
                        </p:column>
                        <p:column headerText="#{msgs.totalprice}">
                            #{(orderDetails.quantity*orderDetails.warehouse.price)}
                        </p:column>
                    </p:dataTable>
                </p:tab>
            </p:tabView>

            <h:panelGroup/>
            <h:panelGroup>
                <h:commandButton value="#{msgs.save}" action="#{orderDetailsBean.save}" styleClass="btn btn-green"/>
                <h:commandButton value="#{msgs.back}" action="#{orderDetailsBean.back}"
                                 styleClass="btn btn-orange m-lft"
                                 immediate="true"/>
            </h:panelGroup>

        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/moderator/orders/list.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/layouts/private.xhtml">

    <ui:define name="top-content">
        <h:form prependId="false">
            <p:commandButton value="#{msgs.search}" actionListener="#{orderDetailsBean.search()}"
                             styleClass="btn btn-blue f-lft" update=":center:table" ajax="true"/>
        </h:form>
    </ui:define>

    <ui:define name="content">
        <h:form id="center">
            <f:view>
                <f:event type="preRenderView" listener="#{orderDetailsBean.init}"/>
            </f:view>
            <p:growl id="poiskGrowl" showDetail="true"/>

            <p:dataTable id="table" var="order" value="#{orderDetailsBean.list}"
                         editable="true" rows="15" rowKey="#{order.id}" lazy="true" multiViewState="true"
                         paginator="true" paginatorPosition="bottom"
                         tableStyleClass="display-table no-border no-bg text-left"
                         paginatorTemplate="{PreviousPageLink} {PageLinks} {NextPageLink} {RowsPerPageDropdown} {CurrentPageReport}">

                <p:column headerText="#{msgs.id}" width="60">
                    <h:outputText value="#{order.id}"/>
                </p:column>
                <p:column headerText="#{msgs.orderid}">
                    <h:outputText value="#{order.orderId}"/>
                </p:column>
                <p:column headerText="#{msgs.fio}">
                    <h:outputText value="#{order.fio}"/>
                </p:column>
                <p:column headerText="#{msgs.flightdate}">
                    <h:outputText value="#{order.flightDate}"/>
                </p:column>
                <p:column headerText="#{msgs.phone}">
                    <h:outputText value="#{order.phone}"/>
                </p:column>
                <p:column headerText="#{msgs.status}">
                    <h:outputText value="#{enums[order.status]}"/>
                </p:column>
                <p:column style="text-align: center; width: 100px">
                    <f:facet name="header">
                        <i class="fa fa-lg fa-gear"/>
                    </f:facet>
                    <p:commandLink action="#{orderDetailsBean.edit(order)}" styleClass="btn-mng" ajax="false">
                        <i class="fa fa-lg fa-pencil"/>
                    </p:commandLink>
                </p:column>
            </p:dataTable>
        </h:form>
    </ui:define>
</ui:composition>