src/main/java/kg/dutyfree/adminsystem/entity/Brands.java
package kg.dutyfree.adminsystem.entity;

import kg.dutyfree.adminsystem.entity.basic.AbstractEntity;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.math.BigInteger;

@Entity
@Table(name = "brands")
@Access(AccessType.PROPERTY)
@ToString
public class Brands extends AbstractEntity<Long> {
    @Setter
    private String name;
    @Setter
    private String description;
    @Setter
    private String image;
    @Setter
    private Category category;

    @Column(name = "brand_name", nullable = true)
    public String getName() {
        return name;
    }

    @Column(name = "brand_description", nullable = true)
    public String getDescription() {
        return description;
    }

    @Column(name = "brand_image")
    public String getImage() {
        return image;
    }

    @ManyToOne
    @JoinColumn(name = "category_id", referencedColumnName = "id")
    public Category getCategory() {
        return category;
    }
}

src/main/java/kg/dutyfree/adminsystem/controller/admin/BrandsBean.java
package kg.dutyfree.adminsystem.controller.admin;

import kg.dutyfree.adminsystem.controller.BaseBean;
import kg.dutyfree.adminsystem.entity.Brands;
import kg.dutyfree.adminsystem.entity.Category;
import kg.dutyfree.adminsystem.service.BrandsService;
import kg.dutyfree.adminsystem.service.CategoryService;
import lombok.Getter;
import lombok.Setter;
import org.primefaces.model.UploadedFile;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.util.Date;
import java.util.List;

@Named
@SessionScoped
public class BrandsBean extends BaseBean<Brands> {
    @EJB
    private BrandsService service;
    @EJB
    private CategoryService categoryService;
    @Override
    public String add() {
        setEntity(new Brands());
        return super.add();
    }

    public String upload(Brands edit) {
        entity = edit;
        return navigate("upload.xhtml");
    }

    @Setter
    @Getter
    private UploadedFile file;

    public String uploadFile() {
        String filePath = this.uploadFile("brand/", file);
        if (filePath!=null){
            entity.setImage(filePath);
            service.merge(entity);
            System.out.println("Successful" + file.getFileName() + " is uploaded.");
            entity=null;
            return navigate("list.xhtml");
        }
        return null;
    }

    public void init(){
//        list=userService.findByExample(0,0, SortEnum.DESCENDING,getFilters(),"basic.addDate");
        list= service.findAll();
    }

    @Override
    public String edit(Brands edit) {
        System.out.println("teste tsetsetkjsdkl ");
        setEntity(edit);
        return super.edit(edit);
    }

    public void delete(Brands delete) {
        service.remove(delete);
    }

    public String save(){
        if(entity.getId()==null){
            basic.setAddDate(new Date());
//            entity.setBasic(basic);
            entity=service.persist(entity);
        }else{
//            entity.getBasic().setChangeDate(new Date());
            entity=service.merge(entity);
        }
        return navigate("list.xhtml");
    }

    public List<Category> getCategories(){
        return categoryService.findAll();
    }
}

src/main/webapp/admin/brands/form.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/layouts/private.xhtml">

    <ui:define name="top-content">

    </ui:define>

    <ui:define name="content">


        <h:form id="form" prependId="false">
            <p:growl sticky="true"/>

            <p:tabView>

                <p:tab title="#{msgs.brand}">
                    <h:panelGrid columns="2" styleClass="form-table" columnClasses="form-table-odd-col"
                                 style="width: 440px;">

                        <h:outputLabel for="name" value="#{msgs.title}"/>
                        <p:inputText value="#{brandsBean.entity.name}" id="name" styleClass="w-1-1"
                                     required="true" requiredMessage="#{msgs.title} - #{errs.requiredField}"/>

                        <h:outputLabel for="surname" value="#{msgs.description}"/>
                        <p:inputText value="#{brandsBean.entity.description}" id="surname" styleClass="w-1-1"
                                     required="true" requiredMessage="#{msgs.description} - #{errs.requiredField}"/>

                        <h:outputLabel for="category" value="#{msgs.category}"/>
                        <p:selectOneMenu id="category" value="#{brandsBean.entity.category}" styleClass="w-1-1"
                                         required="true" requiredMessage="#{msgs.category} - #{errs.requiredField}"
                                         converter="cachedConverter">
                            <f:selectItem itemLabel="#{msgs.selectCategory}" noSelectionOption="true"/>
                            <f:selectItems value="#{brandsBean.categories}" var="cat" itemValue="#{cat}"
                                           itemLabel="#{cat.name}"/>
                        </p:selectOneMenu>

                    </h:panelGrid>
                </p:tab>
            </p:tabView>

            <h:panelGroup/>
            <h:panelGroup>
                <h:commandButton value="#{msgs.save}" action="#{brandsBean.save}" styleClass="btn btn-green"/>
                <h:commandButton value="#{msgs.cancel}" action="#{brandsBean.back}"
                                 styleClass="btn btn-orange m-lft"
                                 immediate="true"/>
            </h:panelGroup>

        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/admin/brands/list.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/layouts/private.xhtml">

    <ui:define name="top-content">
        <h:form prependId="false">
            <h:commandButton value="#{msgs.add}" action="#{brandsBean.add}" styleClass="btn btn-blue f-rht"/>
        </h:form>
    </ui:define>

    <ui:define name="content">
        <h:form id="form" prependId="false">
            <f:view>
                <f:event type="preRenderView" listener="#{brandsBean.init}"/>
            </f:view>
            <p:growl/>
            <p:dataTable id="table" var="brands" value="#{brandsBean.list}"
                         editable="true" rows="25" rowKey="#{brands.id}" lazy="true" multiViewState="true"
                         paginator="true" paginatorPosition="bottom"
                         tableStyleClass="display-table no-border no-bg text-left"
                         paginatorTemplate="{PreviousPageLink} {PageLinks} {NextPageLink} {RowsPerPageDropdown} {CurrentPageReport}">

                <p:column headerText="#{msgs.id}" width="60">
                    <h:outputText value="#{brands.id}"/>
                </p:column>
                <p:column headerText="#{msgs.title}">
                    <h:outputText value="#{brands.name}"/>
                </p:column>
                <p:column headerText="#{msgs.description}">
                    <h:outputText value="#{brands.description}"/>
                </p:column>
                <p:column headerText="#{msgs.categories}">
                    <h:outputText value="#{brands.category.name}"/>
                </p:column>
                <p:column style="text-align: center; width: 100px">
                    <f:facet name="header">
                        <i class="fa fa-lg fa-gear"/>
                    </f:facet>
                    <p:commandLink action="#{brandsBean.edit(brands)}" styleClass="btn-mng" ajax="false">
                        <i class="fa fa-lg fa-pencil"/>
                    </p:commandLink>
                    <p:commandLink action="#{brandsBean.upload(brands)}" rendered="#{brands.image==null}" styleClass="btn-mng" ajax="false">
                        <i class="fa fa-lg fa-upload"/>
                    </p:commandLink>
                    <p:commandLink action="#{brandsBean.delete(brands)}" styleClass="btn-mng" title="#{msgs.delete}"
                                   ajax="false">
                        <p:confirm header="#{msgs.deletion}" message="#{msgs.confirmDeletion}"
                                   icon="ui-icon-alert"/>
                        <i class="fa fa-lg fa-trash"/>
                    </p:commandLink>
                </p:column>
            </p:dataTable>
            <p:confirmDialog global="true" showEffect="fade" closeOnEscape="true" severity="info" id="deletebrands">
                <p:commandLink type="button" styleClass="btn btn-green ui-confirmdialog-yes">
                    <i class="fa fa-lg fa-check"/>
                </p:commandLink>
                <p:commandLink type="button" styleClass="btn btn-red ui-confirmdialog-no m-lft">
                    <i class="fa fa-lg fa-close"/>
                </p:commandLink>
            </p:confirmDialog>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/admin/brands/upload.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/layouts/private.xhtml">

    <ui:define name="top-content">

    </ui:define>

    <ui:define name="content">


        <h:form enctype="multipart/form-data">
            <p:tabView>
                <p:tab title="#{msgs.brands}">
                    <h:panelGrid columns="1" styleClass="form-table" columnClasses="form-table-odd-col"
                                 style="width: 440px;">
                        <h:form enctype="multipart/form-data">
                            <p:fileUpload value="#{brandsBean.file}" mode="simple" skinSimple="true"/>
                            <br/>
                            <h:panelGroup>
                                <h:commandButton value="#{msgs.save}" action="#{brandsBean.uploadFile}" styleClass="btn btn-green"/>
                                <h:commandButton value="#{msgs.cancel}" action="#{brandsBean.back}"
                                                 styleClass="btn btn-orange m-lft"
                                                 immediate="true"/>
                            </h:panelGroup>
                        </h:form>
                    </h:panelGrid>
                </p:tab>
            </p:tabView>
        </h:form>

    </ui:define>
</ui:composition>