src/main/java/kg/dutyfree/adminsystem/entity/Salespoints.java
package kg.dutyfree.adminsystem.entity;

import kg.dutyfree.adminsystem.entity.basic.AbstractEntity;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.math.BigInteger;

@Entity
@Table(name = "salespoints")
@Access(AccessType.PROPERTY)
@ToString
public class Salespoints extends AbstractEntity<Long> {
    @Setter
    private String name;
    @Setter
    private Boolean visible;
    @Setter
    private Tradepoints tradepoint;

    @Column(name = "salespoint_name", nullable = false)
    public String getName() {
        return name;
    }

    @Column(name = "is_visible", nullable = true)
    public Boolean getVisible() {
        return visible;
    }

    @ManyToOne
    @JoinColumn(name = "tradepoint_id", referencedColumnName = "id")
    public Tradepoints getTradepoint() {
        return tradepoint;
    }
}

src/main/java/kg/dutyfree/adminsystem/controller/admin/CurrenciesBean.java
package kg.dutyfree.adminsystem.controller.admin;

import kg.dutyfree.adminsystem.controller.BaseBean;
import kg.dutyfree.adminsystem.entity.Currencies;
import kg.dutyfree.adminsystem.service.CurrenciesService;
import kg.dutyfree.adminsystem.service.CurrenciesService;
import lombok.Getter;
import lombok.Setter;
import org.primefaces.model.UploadedFile;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named
@SessionScoped
public class CurrenciesBean extends BaseBean<Currencies> {
    @EJB
    private CurrenciesService service;
    @Override
    public String add() {
        setEntity(new Currencies());
        return super.add();
    }

    public void init(){
//        list=userService.findByExample(0,0, SortEnum.DESCENDING,getFilters(),"basic.addDate");
        list= service.findAll();
    }

    @Override
    public String edit(Currencies edit) {
        System.out.println("teste tsetsetkjsdkl ");
        setEntity(edit);
        return super.edit(edit);
    }

    public void delete(Currencies delete) {
        service.remove(delete);
    }

    public String save(){
        if(entity.getId()==null){
            entity=service.persist(entity);
        }else{
            entity=service.merge(entity);
        }
        return navigate("list.xhtml");
    }
}

src/main/java/kg/dutyfree/adminsystem/controller/admin/SalespointBean.java
package kg.dutyfree.adminsystem.controller.admin;

import kg.dutyfree.adminsystem.controller.BaseBean;
import kg.dutyfree.adminsystem.entity.Salespoints;
import kg.dutyfree.adminsystem.entity.Tradepoints;
import kg.dutyfree.adminsystem.service.SalespointsService;
import kg.dutyfree.adminsystem.service.SalespointsService;
import kg.dutyfree.adminsystem.service.TradepointsService;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.util.List;

@Named
@SessionScoped
public class SalespointBean extends BaseBean<Salespoints> {
    @EJB
    private SalespointsService service;
    @EJB
    private TradepointsService tradepointsService;
    @Override
    public String add() {
        setEntity(new Salespoints());
        return super.add();
    }

    public void init(){
//        list=userService.findByExample(0,0, SortEnum.DESCENDING,getFilters(),"basic.addDate");
        list= service.findAll();
    }

    @Override
    public String edit(Salespoints edit) {
        System.out.println("teste tsetsetkjsdkl ");
        setEntity(edit);
        return super.edit(edit);
    }

    public void delete(Salespoints delete) {
        service.remove(delete);
    }

    public String save(){
        if(entity.getId()==null){
            entity=service.persist(entity);
        }else{
            entity=service.merge(entity);
        }
        return navigate("list.xhtml");
    }

    public List<Tradepoints> getTradepoints(){
        return tradepointsService.findAll();
    }
}

src/main/webapp/moderator/salespoint/currency.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/layouts/private.xhtml">

    <ui:define name="top-content">

    </ui:define>

    <ui:define name="content">


        <h:form id="form" prependId="false">
            <f:view>
                <f:event type="preRenderView" listener="#{salespointCurrencyBean.init}"/>
            </f:view>
            <p:growl sticky="true"/>

            <p:tabView>

                <p:tab title="#{msgs.salespoint}">
                    <h:panelGrid id="currency" columns="2" styleClass="form-table" columnClasses="form-table-odd-col"
                                 style="width: 440px;">

                        <h:outputLabel for="surname" value="#{msgs.isDefault}"/>
                        <p:selectBooleanCheckbox id="surname" value="#{salespointCurrencyBean.entity.common}" styleClass="w-1-1"
                                                 required="true" requiredMessage="#{msgs.isDefault} - #{errs.requiredField}"/>

                        <h:outputLabel for="tradepoint" value="#{msgs.currencies}"/>
                        <p:selectOneMenu id="tradepoint" value="#{salespointCurrencyBean.entity.currency}" styleClass="w-1-1"
                                         required="true" requiredMessage="#{msgs.tradepoint} - #{errs.requiredField}"
                                         converter="cachedConverter">
                            <f:selectItem itemLabel="#{msgs.selectCurrency}" noSelectionOption="true"/>
                            <f:selectItems value="#{salespointCurrencyBean.currencies}" var="cat" itemValue="#{cat}"
                                           itemLabel="#{cat.name}"/>
                        </p:selectOneMenu>
                        <h:commandButton value="#{msgs.add}" action="#{salespointCurrencyBean.addEntity}"
                                         styleClass="btn btn-blue f-lft m-lft">
                            <f:ajax execute="currency table" render="currency table"/>
                        </h:commandButton>

                    </h:panelGrid>
                    <p:dataTable id="table" value="#{salespointCurrencyBean.list}" var="curr" paginator="false"
                                 tableStyleClass="display-table no-border no-bg text-left">
                        <p:column headerText="#{msgs.title}">
                            #{curr.currency.name}
                        </p:column>
                        <p:column headerText="#{msgs.isDefault}">
                            <p:selectBooleanCheckbox value="#{curr.common}" disabled="true"/>
                        </p:column>
                        <p:column style="width: 50px; text-align: center;">
                            <f:facet name="header">
                                <i class="fa fa-lg fa-gear"/>
                            </f:facet>
                            <p:commandLink action="#{salespointCurrencyBean.delete(curr)}" styleClass="btn-mng"
                                           ajax="false" immediate="true">
                                <i class="fa fa-lg fa-trash"/>
                            </p:commandLink>
                        </p:column>
                    </p:dataTable>
                </p:tab>
            </p:tabView>

            <h:panelGroup/>
            <h:panelGroup>
                <h:commandButton value="#{msgs.back}" action="#{salespointCurrencyBean.back}"
                                 styleClass="btn btn-orange m-lft"
                                 immediate="true"/>
            </h:panelGroup>

        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/moderator/salespoint/details.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/layouts/private.xhtml">

    <ui:define name="top-content">
        <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
        <script type="text/javascript">
            var currentMarker = null;

            function handlePointClick(event) {
                if(currentMarker === null) {
                    document.getElementById('lat').value = event.latLng.lat();
                    document.getElementById('lng').value = event.latLng.lng();

                    currentMarker = new google.maps.Marker({
                        position:new google.maps.LatLng(event.latLng.lat(), event.latLng.lng())
                    });

                    PF('map').addOverlay(currentMarker);

                    PF('dlg').show();
                }
            }

            function markerAddComplete() {
                var title = document.getElementById('title');
                currentMarker.setTitle(title.value);
                title.value = "";

                currentMarker = null;
                PF('dlg').hide();
            }

            function cancel() {
                PF('dlg').hide();
                currentMarker.setMap(null);
                currentMarker = null;

                return false;
            }
        </script>
    </ui:define>

    <ui:define name="content">


        <h:form id="form" prependId="false">
            <p:growl id="messages" showDetail="true" />

            <p:tabView>

                <p:tab title="#{msgs.seller}">
                    <h:panelGrid columns="4" styleClass="form-table" columnClasses="form-table-odd-col"
                                 style="width: 640px;">
                            <p:tab title="#{msgs.map}" >
                                <p:gmap id="gmap" center="42.8646121,74.5308545" zoom="13" type="ROADMAP" style="width:100%;height:400px"
                                        model="#{salespointDetailsBean.emptyModel}" onPointClick="handlePointClick(event);" widgetVar="map" />
                            </p:tab>

                    </h:panelGrid>
                </p:tab>
            </p:tabView>

            <h:panelGroup/>
            <h:panelGroup>
                <h:commandButton value="#{msgs.save}" action="#{salespointDetailsBean.save}" styleClass="btn btn-green"/>
                <h:commandButton value="#{msgs.cancel}" action="#{salespointDetailsBean.back}"
                                 styleClass="btn btn-orange m-lft"
                                 immediate="true"/>
            </h:panelGroup>

            <p:dialog widgetVar="dlg" showEffect="fade">
                <h:panelGrid columns="2">
                    <f:facet name="footer">
                        <p:commandButton value="Add" action="#{salespointDetailsBean.addMarker}" update="messages" oncomplete="markerAddComplete();PF('dlg').hide();" />
                        <p:commandButton value="Cancel" onclick="return cancel()" />
                    </f:facet>
                </h:panelGrid>

                <h:inputHidden id="lat" value="#{salespointDetailsBean.lat}" />
                <h:inputHidden id="lng" value="#{salespointDetailsBean.lon}" />
            </p:dialog>

        </h:form>



    </ui:define>
</ui:composition>

src/main/webapp/moderator/salespoint/form.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/layouts/private.xhtml">

    <ui:define name="top-content">

    </ui:define>

    <ui:define name="content">


        <h:form id="form" prependId="false">
            <p:growl sticky="true"/>

            <p:tabView>

                <p:tab title="#{msgs.salespoint}">
                    <h:panelGrid columns="2" styleClass="form-table" columnClasses="form-table-odd-col"
                                 style="width: 440px;">

                        <h:outputLabel for="name" value="#{msgs.title}"/>
                        <p:inputText value="#{salespointBean.entity.name}" id="name" styleClass="w-1-1"
                                     required="true" requiredMessage="#{msgs.title} - #{errs.requiredField}"/>

                        <h:outputLabel for="surname" value="#{msgs.visible}"/>
                        <p:selectBooleanCheckbox id="surname" value="#{salespointBean.entity.visible}" styleClass="w-1-1"
                                                 required="true" requiredMessage="#{msgs.code} - #{errs.requiredField}"/>

                        <h:outputLabel for="tradepoint" value="#{msgs.tradepoint}"/>
                        <p:selectOneMenu id="tradepoint" value="#{salespointBean.entity.tradepoint}" styleClass="w-1-1"
                                         required="true" requiredMessage="#{msgs.tradepoint} - #{errs.requiredField}"
                                         converter="cachedConverter">
                            <f:selectItem itemLabel="#{msgs.selectTradepoint}" noSelectionOption="true"/>
                            <f:selectItems value="#{salespointBean.tradepoints}" var="cat" itemValue="#{cat}"
                                           itemLabel="#{cat.name}"/>
                        </p:selectOneMenu>

                    </h:panelGrid>
                </p:tab>
            </p:tabView>

            <h:panelGroup/>
            <h:panelGroup>
                <h:commandButton value="#{msgs.save}" action="#{salespointBean.save}" styleClass="btn btn-green"/>
                <h:commandButton value="#{msgs.cancel}" action="#{salespointBean.back}"
                                 styleClass="btn btn-orange m-lft"
                                 immediate="true"/>
            </h:panelGroup>

        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/moderator/salespoint/list.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/layouts/private.xhtml">

    <ui:define name="top-content">
        <h:form prependId="false">
            <h:commandButton value="#{msgs.add}" action="#{salespointBean.add}" styleClass="btn btn-blue f-rht"/>
        </h:form>
    </ui:define>

    <ui:define name="content">
        <h:form id="form" prependId="false">
            <f:view>
                <f:event type="preRenderView" listener="#{salespointBean.init}"/>
            </f:view>
            <p:growl/>
            <p:dataTable id="table" var="salespoint" value="#{salespointBean.list}"
                         editable="true" rows="25" rowKey="#{salespoint.id}" lazy="true" multiViewState="true"
                         paginator="true" paginatorPosition="bottom"
                         tableStyleClass="display-table no-border no-bg text-left"
                         paginatorTemplate="{PreviousPageLink} {PageLinks} {NextPageLink} {RowsPerPageDropdown} {CurrentPageReport}">

                <p:column headerText="#{msgs.id}" width="60">
                    <h:outputText value="#{salespoint.id}"/>
                </p:column>
                <p:column headerText="#{msgs.title}">
                    <h:outputText value="#{salespoint.name}"/>
                </p:column>
                <p:column headerText="#{msgs.visible}">
                    <p:selectBooleanCheckbox value="#{salespoint.visible}" disabled="true"/>
                </p:column>
                <p:column style="text-align: center; width: 150px">
                    <f:facet name="header">
                        <i class="fa fa-lg fa-gear"/>
                    </f:facet>
                    <p:commandLink action="#{salespointBean.edit(salespoint)}" styleClass="btn-mng" ajax="false">
                        <i class="fa fa-lg fa-pencil"/>
                    </p:commandLink>
                    <p:commandLink action="#{salespointDetailsBean.details(salespoint)}" rendered="#{salespoint.id!=null}" styleClass="btn-mng" ajax="false">
                        <i class="fa fa-lg fa-map"/>
                    </p:commandLink>
                    <p:commandLink action="#{salespointCurrencyBean.currecncy(salespoint)}" rendered="#{salespoint.id!=null}" styleClass="btn-mng" ajax="false">
                        <i class="fa fa-lg fa-dollar"/>
                    </p:commandLink>
                    <p:commandLink action="#{salespointBean.delete(salespoint)}" styleClass="btn-mng" title="#{msgs.delete}"
                                   ajax="false">
                        <p:confirm header="#{msgs.deletion}" message="#{msgs.confirmDeletion}"
                                   icon="ui-icon-alert"/>
                        <i class="fa fa-lg fa-trash"/>
                    </p:commandLink>
                </p:column>
            </p:dataTable>
            <p:confirmDialog global="true" showEffect="fade" closeOnEscape="true" severity="info" id="deletesalespoint">
                <p:commandLink type="button" styleClass="btn btn-green ui-confirmdialog-yes">
                    <i class="fa fa-lg fa-check"/>
                </p:commandLink>
                <p:commandLink type="button" styleClass="btn btn-red ui-confirmdialog-no m-lft">
                    <i class="fa fa-lg fa-close"/>
                </p:commandLink>
            </p:confirmDialog>
        </h:form>
    </ui:define>
</ui:composition>